### ISSUE TITLE
plugin install error

### ISSUE THREAD

**Issue by Casmud** [NathanVaughn/poetry-azure-artifacts-plugin#17]
When running `poetry self add poetry-azure-artifacts-plugin` i'm getting following error:

`Because no versions of poetry-azure-artifacts-plugin match >0.1.1,<0.2.0
 and poetry-azure-artifacts-plugin (0.1.1) depends on artifacts-keyring (>=0.3.6,<0.4.0), poetry-azure-artifacts-plugin (>=0.1.1,<0.2.0) requires artifacts-keyring (>=0.3.6,<0.4.0).
So, because poetry-instance depends on both artifacts-keyring (^0.4.0) and poetry-azure-artifacts-plugin (^0.1.1), version solving failed.`

Running `Poetry (version 1.8.3)`

**Comment by Casmud** [comment]
oh well i had to remove the conflicting artifacts-keyring version

**Comment by NathanVaughn** [comment]
Thanks for pointing this out. I will loosen the `artifacts-keyring` version requirement.
